### ISSUE TITLE
reduce ppn?

### ISSUE THREAD

**Issue by soichih** [amnsbr/app-remove-first-volumes#1]
On main, I see that the app is requesting ppn=16. Does this App really use 16 cores? If not, can you reduce it to just 1? It should also set vmem also. 

I recommend something like the following.

```
#PBS -l nodes=1:ppn=1
#PBS -l vmem=8
#PBS -l walltime=02:00:00
```

**Comment by amnsbr** [comment]
Oh no it doesn't need 16 cores. Sorry I missed that. I will change it to your suggestion. Thanks.
